### ISSUE TITLE
[HP Printer] Add support for Officejet 7500 e910

### ISSUE THREAD

**Issue by Cossey** [Cossey/openhab2-addons#13]
Add support for this printer.

**Comment by MDAR** [comment]
For archive purposes - 

[HP_7500_E910.zip](https://github.com/Cossey/openhab2-addons/files/2768956/HP_7500_E910.zip)

**Comment by Cossey** [comment]
This printer has a completely different XML file layout, including additional Consumable Tags with printhead information. Will require a new Type Definition in code.

**Comment by Cossey** [comment]
Device is now supported; there still maybe issues with auto-discovery depending on how the device is labelled. 

Please comment on this issue with the name that the add-on detects if auto-discovery does not work - it is displayed in the log when set to DEBUG level.
