### ISSUE TITLE
[HP Printer] Add support for HP LaserJet 200 color M251nw printer

### ISSUE THREAD

**Issue by Cossey** [Cossey/openhab2-addons#2]
Add support for this printer.

https://www.dropbox.com/s/y3vrnbrwp8nj69s/laserjet200color0m251nw-ProductStatusDyn.xml?dl=0
https://www.dropbox.com/s/lzcqd0nxbiejx59/laserjet200color0m251nw-ProductUsageDyn.xml?dl=0

**Comment by Cossey** [comment]
Added support for basic channels for this printer but still need to test.

**Comment by h4lloween** [comment]
When trying to add the printer manually I get the following error:

```
2019-01-13 14:28:30.491 [WARN ] [ore.thing.internal.ThingRegistryImpl] - Cannot create thing. No binding found that supports creating a thing of type 'hpprinter:laserjetpro200colorm251mw'
```

**Comment by Cossey** [comment]
Thanks for the update, I will try and fix it and get it tested tonight.

**Comment by Cossey** [comment]
Fixed issue with this Thing (the Thing ID was too long and was causing issues).
