### ISSUE TITLE
[HP Printer] Add support for HP Officejet 6600 printer

### ISSUE THREAD

**Issue by Cossey** [Cossey/openhab2-addons#3]
Add support for this printer.

https://www.dropbox.com/s/p7g9it7ingbqu9d/officejet6600-ProductStatusDyn.xml?dl=0
https://www.dropbox.com/s/p7g9it7ingbqu9d/officejet6600-ProductStatusDyn.xml?dl=0

**Comment by Cossey** [comment]
Added support for basic channels for this printer but still need to test it.

**Comment by h4lloween** [comment]
Tested with the latest binding - this printer has 4 color cartridges but the think in openhab only offers 1 channel "Colour Level".

**Comment by Cossey** [comment]
Okay, thanks for the feedback, I'll fix it tonight and give it a test.

**Comment by Cossey** [comment]
Corrected inkLevels to display each colour cart.
