### ISSUE TITLE
[HP Printer] Add JamEvents channel

### ISSUE THREAD

**Issue by Cossey** [Cossey/openhab2-addons#5]
Add Jam Events channel to monitor the amount of jam events on the printer.

**Comment by Cossey** [comment]
Add channel and tested successfully on OfficeJet 8710.

**Comment by sheilbronn** [comment]
Thanks @Cossey for implementing the suggestion so fast! However, I wonder how one could carefully "provoke" a manual test case ;) Does somebody have an idea?

**Comment by Cossey** [comment]
Wouldn't suggest it, lol.

"Fortunately" in my case I had a paper jam the second day because I forgot to correctly adjust the left/right side slider in the the paper tray which caused a jam probably because the feeder pulled it up on a slight angle.
